name: "Test"

on: [push, pull_request]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: 'Python 3.8 on Ubuntu 20.04', python-version: '3.8', os: 'ubuntu-20.04' }
          - { name: 'Python 3.10 on Ubuntu 22.04', python-version: '3.10', os: 'ubuntu-22.04' }
          - { name: 'Python 3.12 on Ubuntu 24.04', python-version: '3.12', os: 'ubuntu-24.04' }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: ./scripts/tests_setup
    - run: pip install -U pip wheel setuptools
    - run: pip install -r dev-requirements.txt

    - run: pytest --log-level=ERROR --disable-warnings -v

  pip-compile:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install -U pip wheel setuptools pip-tools
    - run: pip-compile -U setup.py

  behave:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: 'Python 3.8 on Ubuntu 20.04', python-version: '3.8', os: 'ubuntu-20.04' }
          - { name: 'Python 3.10 on Ubuntu 22.04', python-version: '3.10', os: 'ubuntu-22.04' }
          - { name: 'Python 3.12 on Ubuntu 24.04', python-version: '3.12', os: 'ubuntu-24.04' }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: ./scripts/tests_setup
    - run: pip install -U pip wheel setuptools
    - run: pip install -r dev-requirements.txt

    - run: behave --tags=-sams --format progress2 --logging-level=ERROR

  behave-sams:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: 'Python 3.8 on Ubuntu 20.04', python-version: '3.8', os: 'ubuntu-20.04' }
          - { name: 'Python 3.10 on Ubuntu 22.04', python-version: '3.10', os: 'ubuntu-22.04' }
          - { name: 'Python 3.12 on Ubuntu 24.04', python-version: '3.12', os: 'ubuntu-24.04' }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: ./scripts/tests_setup
    - run: ./scripts/install-start-sams

    - run: pip install -U pip wheel setuptools
    - run: pip install -r dev-requirements.txt

    - run: behave --tags=sams --format progress2 --logging-level=ERROR

  prodapi:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: 'Python 3.8 on Ubuntu 20.04', python-version: '3.8', os: 'ubuntu-20.04' }
          - { name: 'Python 3.10 on Ubuntu 22.04', python-version: '3.10', os: 'ubuntu-22.04' }
          - { name: 'Python 3.12 on Ubuntu 24.04', python-version: '3.12', os: 'ubuntu-24.04' }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: ./scripts/tests_setup
    - run: pip install -U pip wheel setuptools
    - run: pip install -r dev-requirements.txt

    - run: pytest prod_api
